name: "\U0001F41B [Bug report]:"
description: Create a report to help us improve
title: "\U0001F41B [Bug report]: "
labels: ['bug']
assignees: ['']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug?
      description: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce-step
    attributes:
      label: Steps to reproduce the bug?
      description: Steps to reproduce the behavior..
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: desktop-details
    attributes:
      label: Desktop (Please provide your system information)
      description: |
        examples:
          - **OS**: [e.g. iOS]
          - **Browser** [e.g. chrome, safari]
          - **Version** [e.g. 22]
    validations:
      required: true

  - type: textarea
    id: mobile-browser
    attributes:
      label: Mobile (Please provide your device information)
      description: |
        examples:
           - **Device**: [e.g. iPhone6]
           - **OS**: [e.g. iOS8.1]
           - **Browser** [e.g. stock browser, safari]
           - **Version** [e.g. 22]
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot / ScreenShare
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: Relevant log output
      description: Add any other context about the problem here.
      render: shell-script

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
